version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 9000:7777
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE : everytown
      MYSQL_USER: ykgod
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234
